server:
  port: 9005

eureka:
  instance:
    prefer-ip-address: true

  client:
    # 天啊，是ture字符went
    register-with-eureka: true # 为什么idea能够自动识别这些前缀？
    fetch-registry: true # 拉取注册表的本地副本

    service-url:
      # add
      defaultZone: http://127.0.0.1:8761/eureka/
