server:
    port: 8081
spring:
  # the configuration of service for redisTemplate
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 100
      min-idel: 1
      max-active: 1000
      max-wait: -1 # 等待时间